import History from "./history.jpg";
import Logo from "./logo.png";
export default () => {
  const home = document.createElement("div");
  home.classList.add("module");
  home.setAttribute("id", "home");
  const header = document.createElement("div");
  header.classList.add("header");
  const logo = new Image();
  logo.src = Logo;
  logo.classList.add("logo");
  const motto = document.createElement("h1");
  motto.textContent = "Welcome to Delicious Eats";
  header.appendChild(logo);
  header.appendChild(motto);
  const history = document.createElement("div");
  history.classList.add("history");
  const historyText = document.createElement("p");
  historyText.textContent =
    "Delicious Eats has been serving mouthwatering dishes since 2005. Our mission is to provide high-quality, flavorful meals that leave our customers craving for more. Whether you're looking for traditional favorites or innovative culinary creations, we have something for everyone.";
  const historyImage = new Image();
  historyImage.src = History;
  historyImage.classList.add("history-image");
  history.appendChild(historyText);
  history.appendChild(historyImage);
  const branches = document.createElement("div");
  branches.classList.add("branches");
  const branchesTitle = document.createElement("h2");
  branchesTitle.textContent = "Our Branches";
  branches.appendChild(branchesTitle);
  const branchList = document.createElement("ul");
  const branch1 = document.createElement("li");
  branch1.textContent = "Downtown Location: 123 Main Street, (555) 123-4567";
  branchList.appendChild(branch1);
  const branch2 = document.createElement("li");
  branch2.textContent = "Westside Location: 789 Elm Avenue, (555) 987-6543";
  branchList.appendChild(branch2);
  branches.appendChild(branchList);
  const hours = document.createElement("div");
  hours.classList.add("hours");
  const hoursTitle = document.createElement("h2");
  hoursTitle.textContent = "Opening Hours";
  const hoursTable = document.createElement("table");
  const tableHeaderRow = document.createElement("tr");
  const mondayHeaderCell = document.createElement("th");
  mondayHeaderCell.textContent = "Monday";
  tableHeaderRow.appendChild(mondayHeaderCell);
  const tuesdayHeaderCell = document.createElement("th");
  tuesdayHeaderCell.textContent = "Tuesday";
  tableHeaderRow.appendChild(tuesdayHeaderCell);
  hoursTable.appendChild(tableHeaderRow);
  const tableDataRow = document.createElement("tr");
  const mondayDataCell = document.createElement("td");
  mondayDataCell.textContent = "9:00 AM - 10:00 PM";
  tableDataRow.appendChild(mondayDataCell);
  const tuesdayDataCell = document.createElement("td");
  tuesdayDataCell.textContent = "9:00 AM - 10:00 PM";
  tableDataRow.appendChild(tuesdayDataCell);
  hoursTable.appendChild(tableDataRow);
  hours.appendChild(hoursTitle);
  hours.appendChild(hoursTable);
  home.appendChild(header);
  home.appendChild(history);
  home.appendChild(branches);
  home.appendChild(hours);
  return home;
};
